export const BUILTIN_SKILLS = [
  { id: "general-assistant", name: "General Assistant", description: "Planning, writing, reasoning, everyday tasks.", icon: "Sparkles" },
  { id: "research", name: "Research", description: "Search the web, read pages, and build cited research reports.", icon: "Search" },
  { id: "content-creation", name: "Content Creation", description: "Draft posts and copy in a chosen voice.", icon: "PenLine" },
  { id: "data-analysis", name: "Data Analysis", description: "Interpret tables and surface patterns.", icon: "BarChart3" },
  { id: "marketing", name: "Marketing", description: "Plan campaigns, audiences, and messaging.", icon: "Megaphone" },
  { id: "productivity", name: "Productivity", description: "Organize tasks, schedules, and workflows.", icon: "ListChecks" },
  { id: "memory", name: "Memory", description: "Remember and recall information across conversations.", icon: "BrainCircuit" },
  { id: "meta_ads", name: "Meta Ads", description: "Manage Meta ad campaigns once your account is connected.", icon: "Radar" },
  { id: "whatsapp", name: "WhatsApp Business", description: "Send and manage WhatsApp conversations once your account is connected.", icon: "MessageCircle" },
  { id: "automations", name: "Automations", description: "Build and run automated workflows across your other skills and tools.", icon: "Workflow" },
  { id: "wordpress", name: "WordPress", description: "Manage posts, pages, and media once your site is connected.", icon: "Globe" },
  { id: "woocommerce", name: "WooCommerce", description: "Manage products, orders, and customers once your store is connected.", icon: "ShoppingCart" },
  { id: "gmail", name: "Gmail", description: "Read, search, and send email once your account is connected.", icon: "Mail" },
  { id: "calendar", name: "Google Calendar", description: "View and manage calendar events once your account is connected.", icon: "Calendar" },
  { id: "drive", name: "Google Drive", description: "List, search, create, and share Drive files once your account is connected.", icon: "HardDrive" },
  { id: "docs", name: "Google Docs", description: "Create, read, and edit Google Docs once your account is connected.", icon: "FileText" },
  { id: "sheets", name: "Google Sheets", description: "Create spreadsheets and read/write cell data once your account is connected.", icon: "Table" },
  { id: "shopify", name: "Shopify", description: "Manage products, orders, customers, inventory, discounts, and collections once your store is connected.", icon: "ShoppingBag" },
  { id: "collaboration", name: "Agent Collaboration", description: "Delegate tasks to your other agents and chain them together on multi-step work.", icon: "Share2" },
  { id: "custom_tools", name: "Custom Tools (Developer)", description: "Use tools you've built and published yourself via the Developer SDK — each one calls a webhook you host.", icon: "Webhook" },
  { id: "seo", name: "SEO Audit", description: "Audit a page's on-page SEO (title, meta description, headings, alt text) and check Core Web Vitals / page speed.", icon: "TrendingUp" },
  { id: "meta_expert", name: "Meta Ads Expert Planner", description: "Research business/account context and build a validated, approval-gated Meta campaign strategy from a stated goal, instead of guessing individual campaign settings.", icon: "Target" },
];
